spring:
  profiles:
    active: chaos-monkey
chaos:
  monkey:
    enabled: true
    watcher:
      rest-controller: true
    assaults:
      latencyActive: true
      level: 1
      latency-range-start: 3000
      latency-range-end: 5000
      exception:
        type: org.springframework.web.client.RestClientException
        method: <init>
      exceptions-active: false
      watched-custom-services:
        - com.chaos.monkey.SimpleApiAdapter

management:
  endpoint:
    chaosmonkey:
      enabled: true

  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - chaosmonkey